# Generated by Django 2.2.12 on 2022-04-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0002_item_shipping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shipping_charge',
        ),
    ]
