# Generated by Django 2.2.12 on 2022-03-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='logo',
            field=models.ImageField(default='', upload_to='Menubar_brand_log'),
        ),
    ]
