# Generated by Django 2.2.12 on 2022-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_categ_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='extra_reduce_amound',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='model_img',
            field=models.ImageField(default='', upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='off_prize',
            field=models.CharField(default='', max_length=20),
        ),
    ]
