# Generated by Django 2.2.12 on 2022-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_auto_20220328_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='off_prize2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='pecentage_off',
            field=models.CharField(default='', max_length=100),
        ),
    ]
