# Generated by Django 2.2.12 on 2022-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mobile_feature1',
            field=models.TextField(default=''),
        ),
    ]
