# Generated by Django 2.2.12 on 2022-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0006_products_mobile_feature1'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mobile_feature2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='mobile_feature3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='mobile_feature4',
            field=models.TextField(default=''),
        ),
    ]
