# Generated by Django 2.2.12 on 2022-03-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0010_auto_20220328_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='extra_reduce_amound',
            new_name='browse_type',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='pecentage_off',
            new_name='display',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='megha_pixel',
            new_name='mega_pixel',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='display_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='extra_reduce_amount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='in_the_box',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='model_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='percentage_off',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='sim_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
