# Generated by Django 2.2.12 on 2022-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0012_products_model_ram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='model_ram',
            new_name='model_RAM',
        ),
        migrations.AddField(
            model_name='products',
            name='model_ROM',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
