# Generated by Django 2.2.12 on 2022-03-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0015_auto_20220329_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Warranty_details',
            field=models.URLField(default='', max_length=500),
        ),
    ]
