# Generated by Django 2.2.12 on 2022-03-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0016_products_warranty_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='read_more_link',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='view_all_features_link',
            field=models.URLField(default='', max_length=500),
        ),
    ]
