# Generated by Django 2.2.12 on 2022-03-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0017_auto_20220329_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Warranty_details',
            new_name='Warranty_details_link',
        ),
    ]
