# Generated by Django 2.2.12 on 2022-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0018_auto_20220329_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='percentage_off',
            field=models.IntegerField(),
        ),
    ]
