# Generated by Django 2.2.12 on 2022-04-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0019_auto_20220406_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='off_prize2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='percentage_off',
            field=models.CharField(default='', max_length=100),
        ),
    ]
