# Generated by Django 2.2.12 on 2022-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0021_auto_20220406_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='percentage_off',
            field=models.IntegerField(),
        ),
    ]
